services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - ./.env
    volumes:
      - ./.env:/app/.env:rw
    ports:
      - "8000:8000"
  # Add frontend later